services:
  pg_media:
    restart: always
    container_name: pg_media
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=uo_media
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../../migrations/20240926145319_mediaAd.up.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d uo_media"]
      interval: 10s
      timeout: 5s
      retries: 5

  rdb_media:
    restart: always
    image: redis:latest
    container_name: rdb_media
    environment:
      REDIS_PASSWORD: redis
    ports:
      - "6379:6379"

  media:
    restart: always
    container_name: media
    command: "air -c .air.toml"
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
    ports:
      - "8080:8080"
    env_file:
      - ../../.env
    depends_on:
      pg_media:
        condition: service_healthy
      rdb_media:
        condition: service_started

volumes:
  pgdata:
    driver: local
