// Code generated by ogen, DO NOT EDIT.
package api

type V1AdminAdsGetRes interface {
	v1AdminAdsGetRes()
}

type V1AdminAdsIDDeleteRes interface {
	v1AdminAdsIDDeleteRes()
}

type V1AdminAdsIDPutRes interface {
	v1AdminAdsIDPutRes()
}

type V1AdminAdsPostRes interface {
	v1AdminAdsPostRes()
}

type V1AdminColorsGetRes interface {
	v1AdminColorsGetRes()
}

type V1AdminColorsIDDeleteRes interface {
	v1AdminColorsIDDeleteRes()
}

type V1AdminColorsIDPutRes interface {
	v1AdminColorsIDPutRes()
}

type V1AdminColorsPostRes interface {
	v1AdminColorsPostRes()
}

type V1AdminImagesGetRes interface {
	v1AdminImagesGetRes()
}

type V1AdminImagesIDDeleteRes interface {
	v1AdminImagesIDDeleteRes()
}

type V1AdminImagesIDPutRes interface {
	v1AdminImagesIDPutRes()
}

type V1AdminImagesPostRes interface {
	v1AdminImagesPostRes()
}

type V1AdminTgsGetRes interface {
	v1AdminTgsGetRes()
}

type V1AdminTgsIDDeleteRes interface {
	v1AdminTgsIDDeleteRes()
}

type V1AdminTgsIDPutRes interface {
	v1AdminTgsIDPutRes()
}

type V1AdminTgsPostRes interface {
	v1AdminTgsPostRes()
}

type V1AdsGetRes interface {
	v1AdsGetRes()
}

type V1LogosGetRes interface {
	v1LogosGetRes()
}
