// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuthUC is an autogenerated mock type for the AuthUC type
type AuthUC struct {
	mock.Mock
}

// GetUserRoleFromToken provides a mock function with given fields: jwtToken
func (_m *AuthUC) GetUserRoleFromToken(jwtToken string) (string, error) {
	ret := _m.Called(jwtToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoleFromToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(jwtToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(jwtToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(jwtToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsUserAdmin provides a mock function with given fields: userRole
func (_m *AuthUC) IsUserAdmin(userRole string) bool {
	ret := _m.Called(userRole)

	if len(ret) == 0 {
		panic("no return value specified for IsUserAdmin")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(userRole)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewAuthUC creates a new instance of AuthUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUC {
	mock := &AuthUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
