// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuthSrv is an autogenerated mock type for the AuthSrv type
type AuthSrv struct {
	mock.Mock
}

// GetUserRoleFromToken provides a mock function with given fields: jwtToken
func (_m *AuthSrv) GetUserRoleFromToken(jwtToken string) (string, error) {
	ret := _m.Called(jwtToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoleFromToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(jwtToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(jwtToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(jwtToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsUserAuthorized provides a mock function with given fields: requiredRole, userRole
func (_m *AuthSrv) IsUserAuthorized(requiredRole string, userRole string) bool {
	ret := _m.Called(requiredRole, userRole)

	if len(ret) == 0 {
		panic("no return value specified for IsUserAuthorized")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(requiredRole, userRole)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewAuthSrv creates a new instance of AuthSrv. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthSrv(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthSrv {
	mock := &AuthSrv{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
