// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/himmel520/uoffer/mediaAd/internal/models"
)

// TGSrv is an autogenerated mock type for the TGSrv type
type TGSrv struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, tg
func (_m *TGSrv) Add(ctx context.Context, tg *models.TG) (*models.TGResp, error) {
	ret := _m.Called(ctx, tg)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *models.TGResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TG) (*models.TGResp, error)); ok {
		return rf(ctx, tg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.TG) *models.TGResp); ok {
		r0 = rf(ctx, tg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TGResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.TG) error); ok {
		r1 = rf(ctx, tg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TGSrv) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllWithPagination provides a mock function with given fields: ctx, limit, offset
func (_m *TGSrv) GetAllWithPagination(ctx context.Context, limit int, offset int) (*models.TGsResp, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllWithPagination")
	}

	var r0 *models.TGsResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*models.TGsResp, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *models.TGsResp); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TGsResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, TG
func (_m *TGSrv) Update(ctx context.Context, id int, TG *models.TGUpdate) (*models.TGResp, error) {
	ret := _m.Called(ctx, id, TG)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.TGResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.TGUpdate) (*models.TGResp, error)); ok {
		return rf(ctx, id, TG)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.TGUpdate) *models.TGResp); ok {
		r0 = rf(ctx, id, TG)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TGResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *models.TGUpdate) error); ok {
		r1 = rf(ctx, id, TG)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTGSrv creates a new instance of TGSrv. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTGSrv(t interface {
	mock.TestingT
	Cleanup(func())
}) *TGSrv {
	mock := &TGSrv{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
